openapi: 3.0.0
info:
  description: Andmejälgija kasutusteabe küsimise teenus
  version: 1.0.0
  title: Andmejälgija kasutusteabe
  contact:
    email: help@ria.ee
tags:
- name: usage
  description: Andmejälgija kasutusteabe
paths:
  /findUsage:
    get:
      tags:
      - usage
      summary: Kasutusteabe küsimine
      description: Andmejälgija kasutusteabe küsimine andmesubjektile kuvamiseks
      operationId: findUsage
      parameters:
      - name: X-Road-UserId
        in: header
        schema:
          type: string
          example: "EE12345678901"
          description: Andmesubjekti isikukood peab olema lisatud X-Road päise sisse
          externalDocs:
            description: Täiendav informatsioon X-Road päiste kohta
            url: 'https://x-tee.ee/docs/live/xroad/pr-rest_x-road_message_protocol_for_rest.html'
        required: true
      - name: offset
        in: query
        description: Tagastada kirjed, mille järjekorranumber on alates näidatud täisarvust (esimese kirje järjekorranumber on 1).
        required: false
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: Tagastata maksimaalselt näidatud arv kirjeid (vaikimisi tagastatakse maksimaalselt 100 kirjet).
        required: false
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usage'
        '400':
          description: Päringu sisu ei vasta nõuetele
        '500':
          description: Päringu täitmisel juhtus viga
components:
  schemas:
    Usage:
      type: object
      properties:
        logtime:
          description: Kirje ajamoment.
          type: string
          format: date-time
          example: "2021-01-31T10:20:30"
        action:
          description: Menetluse/tegevuse inimmõistetav nimi.
          type: string
          example: "Isiku ees- ja perenime päring"
        receiver:
          description: Asutuse kood, kellele isikuandmeid edastati.
          type: string
          example: "Riigiportaal"
